name: Project Assignment CI Pipeline on Quarkus

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:   # allows manual trigger from GitHub UI

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Upgrade Docker Engine
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Set timezone to UTC
        run: echo "TZ=UTC" >> $GITHUB_ENV

      - name: Give mvnw execute permission
        run: chmod +x ./mvnw

      - name: Build and run tests
        run: ./mvnw -B clean verify -Duser.timezone=UTC

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: target/
